# Generated by Django 3.2.12 on 2025-09-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=30)),
                ('total', models.FloatField(default=0.0)),
                ('account_name', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=150)),
            ],
        ),
    ]
