# Generated by Django 4.2.24 on 2025-11-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.FloatField(blank=True, help_text='Credit limit for credit card accounts', null=True),
        ),
    ]
