# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_credit_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="account",
            name="bank",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_name",
            field=models.CharField(max_length=120),
        ),
    ]
