# Generated by Django 5.2.17 on 2026-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_credit_card_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='account_acc_owner_u_012189_idx',
            old_name='account_acc_owner__0a182f_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='account_acc_owner_967175_idx',
            old_name='account_acc_owner_79209f_idx',
        ),
    ]
