# Generated by Django 5.2.17 on 2026-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_owner_u_dbe3ac_idx',
            old_name='alerts_aler_owner_u_c8d416_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_owner_u_5e887a_idx',
            old_name='alerts_aler_owner_u_809a76_idx',
        ),
    ]
