# Generated by Django 5.2.17 on 2026-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_enable_pg_stat_statements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authtoken',
            new_name='users_autht_user_id_c1eeb0_idx',
            old_name='users_autht_user_id_7e0a7e_idx',
        ),
        migrations.RenameIndex(
            model_name='authtoken',
            new_name='users_autht_revoked_710523_idx',
            old_name='users_autht_revoked_d46eb4_idx',
        ),
    ]
