# Generated by Django 5.2.17 on 2026-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recurringoccurrence',
            new_name='recurring_r_owner_u_3c29fa_idx',
            old_name='recurring_re_owner__076b6a_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringtransaction',
            new_name='recurring_r_owner_u_385707_idx',
            old_name='recurring_re_owner__7cd1b4_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringtransaction',
            new_name='recurring_r_owner_u_147dfd_idx',
            old_name='recurring_re_owner__c7c1af_idx',
        ),
    ]
