# Generated by Django 4.2.24 on 2025-09-19 04:55

import bankstatements.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='Username of the user who uploaded the statement', max_length=150)),
                ('file', models.FileField(help_text='PDF file of the bank statement', upload_to=bankstatements.models.bank_statement_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('original_filename', models.CharField(help_text='Original filename of the uploaded file', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='Size of the file in bytes')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the file was uploaded')),
                ('processed', models.BooleanField(default=False, help_text='Whether the statement has been processed by AI')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-upload_date'],
            },
        ),
    ]
