# Generated by Django 5.0.14 on 2026-10-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bankstatements", "0006_credit_card_deferred_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatementtransactioncandidate",
            name="destination_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_candidates",
                to="bankstatements.bankstatementimportproduct",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementtransactioncandidate",
            name="source_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_candidates",
                to="bankstatements.bankstatementimportproduct",
            ),
        ),
    ]
