# Generated by Django 5.2.17 on 2026-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankstatements', '0009_import_product_bank_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='bankstateme_owner_u_9a12f4_idx',
            old_name='bankstatem_owner__6ecb53_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='bankstateme_user_id_970a8a_idx',
            old_name='bankstatem_user_id_f7c4f8_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementimportbatch',
            new_name='bankstateme_owner_u_93e8c9_idx',
            old_name='bankstatem_owner_u_6d8358_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementimportbatch',
            new_name='bankstateme_bank_st_10cd5a_idx',
            old_name='bankstatem_bank_st_b51032_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementtransactioncandidate',
            new_name='bankstateme_owner_u_f173d5_idx',
            old_name='bankstatem_owner_u_f3d094_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementtransactioncandidate',
            new_name='bankstateme_import__528550_idx',
            old_name='bankstatem_import_13f46e_idx',
        ),
    ]
