# Generated by Django 4.2.5 on 2023-10-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('total', models.FloatField(default=0.0)),
                ('owner_id', models.CharField(max_length=20)),
                ('account_id', models.CharField(max_length=20)),
            ],
        ),
    ]
