# Generated by Django 4.2.24 on 2025-11-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_account_id',
            field=models.CharField(blank=True, help_text='Source account (for transfers)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account_id',
            field=models.CharField(blank=True, help_text='Destination account (for transfers)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_id',
            field=models.CharField(blank=True, help_text='Legacy: single account for income/expense', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Transfer', 'Transfer')], max_length=30),
        ),
    ]
