# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_transaction_from_account_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
