# Generated by Django 5.2.17 on 2026-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_owner_account_fks_decimal_money'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_owner_u_ffed42_idx',
            old_name='transactio_owner__2798ec_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_owner_i_094b11_idx',
            old_name='transactio_owner__3934db_idx',
        ),
    ]
