# Generated by Django 5.2.17 on 2026-10-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='budget',
            new_name='budgets_bud_owner_u_0c4249_idx',
            old_name='budgets_bud_owner_u_bba93b_idx',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='budgets_bud_owner_u_d762ca_idx',
            old_name='budgets_bud_owner_u_6a7772_idx',
        ),
    ]
